"use client";

import dynamic from "next/dynamic";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

import { Button } from "@/components/ui/button";

import { Download, Loader2, FileDown, Sparkles } from "lucide-react";

const PDFDownloadLink = dynamic(
  () => import("@react-pdf/renderer").then((mod) => mod.PDFDownloadLink),
  { ssr: false },
);

const styles = StyleSheet.create({
  page: {
    paddingTop: 45,
    paddingBottom: 45,
    paddingHorizontal: 38,
    fontSize: 11,
    lineHeight: 1.8,
    fontFamily: "Helvetica",
    backgroundColor: "#f8fafc",
    color: "#111827",
  },

  header: {
    marginBottom: 30,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },

  brand: {
    fontSize: 12,
    color: "#6366f1",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    marginBottom: 8,
    fontWeight: "bold",
  },

  title: {
    fontSize: 28,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#111827",
  },

  description: {
    fontSize: 11,
    color: "#6b7280",
    lineHeight: 1.6,
  },

  scoreCard: {
    backgroundColor: "#111827",
    borderRadius: 16,
    paddingVertical: 28,
    paddingHorizontal: 24,
    marginBottom: 30,
    textAlign: "center",
  },

  scoreLabel: {
    fontSize: 11,
    color: "#9ca3af",
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },

  score: {
    fontSize: 54,
    color: "#10b981",
    fontWeight: "bold",
  },

  scoreText: {
    marginTop: 10,
    color: "#d1d5db",
    fontSize: 11,
  },

  infoGrid: {
    flexDirection: "row",
    gap: 16,
    marginBottom: 28,
  },

  infoCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },

  infoTitle: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#111827",
  },

  infoText: {
    fontSize: 10,
    color: "#6b7280",
    lineHeight: 1.7,
  },

  section: {
    marginTop: 10,
  },

  sectionTitle: {
    fontSize: 18,
    marginBottom: 14,
    fontWeight: "bold",
    color: "#111827",
  },

  analysisContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 22,
    borderWidth: 1,
    borderColor: "#e5e7eb",
  },

  analysisText: {
    fontSize: 11,
    color: "#374151",
    lineHeight: 1.9,
  },

  footer: {
    marginTop: 35,
    paddingTop: 18,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
    textAlign: "center",
    fontSize: 10,
    color: "#9ca3af",
  },
});

interface ReportPDFProps {
  report: any;
}

function ReportDocument({ report }: ReportPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.brand}>RoleNorth AI</Text>

          <Text style={styles.title}>Career Analysis Report</Text>

          <Text style={styles.description}>
            AI-powered resume intelligence report with ATS evaluation, career
            growth insights, and future-proof recommendations.
          </Text>
        </View>

        {/* ATS Score */}
        <View style={styles.scoreCard}>
          <Text style={styles.scoreLabel}>ATS Compatibility Score</Text>

          <Text style={styles.score}>{report.ats_score}/100</Text>

          <Text style={styles.scoreText}>
            Generated on{" "}
            {new Date(report.created_at).toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </Text>
        </View>

        {/* Insight Cards */}
        <View style={styles.infoGrid}>
          <View style={styles.infoCard}>
            <Text style={styles.infoTitle}>Resume Intelligence</Text>

            <Text style={styles.infoText}>
              Deep AI evaluation of resume structure, keyword optimization,
              readability, and ATS compatibility.
            </Text>
          </View>

          <View style={styles.infoCard}>
            <Text style={styles.infoTitle}>Career Insights</Text>

            <Text style={styles.infoText}>
              Personalized analysis covering strengths, weaknesses, automation
              exposure, and growth opportunities.
            </Text>
          </View>
        </View>

        {/* Full Analysis */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Full Career Analysis</Text>

          <View style={styles.analysisContainer}>
            <Text style={styles.analysisText}>{report.analysis}</Text>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer}>
          <Text>Generated by RoleNorth • AI Career Intelligence Platform</Text>
        </View>
      </Page>
    </Document>
  );
}

export function DownloadPDFButton({ report }: { report: any }) {
  return (
    <PDFDownloadLink
      document={<ReportDocument report={report} />}
      fileName={`rolenorth-report-${
        new Date().toISOString().split("T")[0]
      }.pdf`}
    >
      {({ loading }: { loading: boolean }) => (
        <Button
          disabled={loading}
          className="group h-12 rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 px-6 text-white shadow-lg transition-all hover:scale-[1.02] hover:shadow-xl"
        >
          {loading ? (
            <>
              <Loader2 className="mr-2 h-5 w-5 animate-spin" />
              Generating PDF...
            </>
          ) : (
            <>
              <div className="mr-2 rounded-full bg-white/20 p-1">
                <FileDown className="h-4 w-4" />
              </div>
              Download PDF
              <Sparkles className="ml-2 h-4 w-4 opacity-80" />
            </>
          )}
        </Button>
      )}
    </PDFDownloadLink>
  );
}